# Configurações do Repositório Vytalle Estética
name: "Vytalle Estética - E-commerce B2B Premium"
description: "Catálogo B2B de produtos médicos estéticos premium - Next.js 14 + Supabase + Tailwind CSS. Distribuição de toxinas botulínicas, preenchedores e bioestimuladores certificados ANVISA."
homepage: "https://vytalle-estetica.vercel.app"
topics:
  - "vytalle"
  - "estetica"
  - "ecommerce"
  - "b2b"
  - "nextjs"
  - "supabase"
  - "tailwindcss"
  - "typescript"
  - "pwa"
  - "medical-aesthetics"
  - "botox"
  - "preenchedores"
  - "bioestimuladores"
  - "anvisa"
  - "lgpd"
  - "vercel"
  - "vitest"
  - "playwright"
  - "github-actions"
  - "ci-cd"

# Configurações de visibilidade
private: false
has_issues: true
has_projects: true
has_wiki: false
has_downloads: true
default_branch: "main"
allow_squash_merge: true
allow_merge_commit: true
allow_rebase_merge: true
delete_branch_on_merge: true

# Configurações de segurança
vulnerability_alerts: true
automated_security_fixes: true 