/**
 * DADOS MÍNIMOS DOS PRODUTOS - VYTALLE ESTÉTICA
 * ============================================
 *
 * Dados extraídos automaticamente do mockData.ts
 * Apenas informações essenciais para reduzir uso de memória
 */

// Interface para produto minimizado
export interface ProductMinimal {
  id: string;
  name: string;
  price_pix: number;
  price_prazo: number;
  price_card: number;
  category: string;
  slug: string;
  active: boolean;
}

// Dados dos produtos (apenas essenciais, sem imagens)
export const productsMinimalData: ProductMinimal[] = [
  {
    id: '1',
    name: 'DL BOTOX 100UI',
    price_pix: 745,
    price_prazo: 789,
    price_card: 789,
    category: 'Toxina Botulínica',
    slug: 'dl-botox-100ui',
    active: true,
  },
  {
    id: '2',
    name: 'DL BOTOX 200UI',
    price_pix: 1365,
    price_prazo: 1399,
    price_card: 1399,
    category: 'Toxina Botulínica',
    slug: 'dl-botox-200ui',
    active: true,
  },
  {
    id: '3',
    name: 'DL BOTOX 50UI',
    price_pix: 489,
    price_prazo: 525,
    price_card: 525,
    category: 'Toxina Botulínica',
    slug: 'dl-botox-50ui',
    active: true,
  },
  {
    id: '4',
    name: 'DL BOTULIFT 100UI',
    price_pix: 775,
    price_prazo: 791,
    price_card: 791,
    category: 'Toxina Botulínica',
    slug: 'dl-botulift-100ui',
    active: true,
  },
  {
    id: '5',
    name: 'DL BOTULIFT 150UI',
    price_pix: 940,
    price_prazo: 973,
    price_card: 973,
    category: 'Toxina Botulínica',
    slug: 'dl-botulift-150ui',
    active: true,
  },
  {
    id: '6',
    name: 'DL BOTULIFT 200UI',
    price_pix: 1245,
    price_prazo: 1273,
    price_card: 1273,
    category: 'Toxina Botulínica',
    slug: 'dl-botulift-200ui',
    active: true,
  },
  {
    id: '7',
    name: 'DL BOTULIM 100UI',
    price_pix: 649,
    price_prazo: 689,
    price_card: 689,
    category: 'Toxina Botulínica',
    slug: 'dl-botulim-100ui',
    active: true,
  },
  {
    id: '8',
    name: 'DL BOTULIM 200UI',
    price_pix: 1065,
    price_prazo: 1099,
    price_card: 1099,
    category: 'Toxina Botulínica',
    slug: 'dl-botulim-200ui',
    active: true,
  },
  {
    id: '9',
    name: 'DL BOTULIM 50UI',
    price_pix: 499,
    price_prazo: 525,
    price_card: 525,
    category: 'Toxina Botulínica',
    slug: 'dl-botulim-50ui',
    active: true,
  },
  {
    id: '10',
    name: 'DL DYSPORT 300UI',
    price_pix: 990,
    price_prazo: 1090,
    price_card: 1090,
    category: 'Toxina Botulínica',
    slug: 'dl-dysport-300ui',
    active: true,
  },
  {
    id: '11',
    name: 'DL DYSPORT 500UI',
    price_pix: 1359,
    price_prazo: 1459,
    price_card: 1459,
    category: 'Toxina Botulínica',
    slug: 'dl-dysport-500ui',
    active: true,
  },
  {
    id: '12',
    name: 'DL NABOTA 100UI',
    price_pix: 620,
    price_prazo: 649,
    price_card: 649,
    category: 'Toxina Botulínica',
    slug: 'dl-nabota-100ui',
    active: true,
  },
  {
    id: '13',
    name: 'DL XEOMIN 100UI',
    price_pix: 620,
    price_prazo: 645,
    price_card: 645,
    category: 'Toxina Botulínica',
    slug: 'dl-xeomin-100ui',
    active: true,
  },
  {
    id: '14',
    name: 'DL ELLANSE M',
    price_pix: 1149,
    price_prazo: 1199,
    price_card: 1199,
    category: 'Bioestimuladores',
    slug: 'dl-ellanse-m',
    active: true,
  },
  {
    id: '15',
    name: 'DL ELLANSE S',
    price_pix: 965,
    price_prazo: 999,
    price_card: 999,
    category: 'Bioestimuladores',
    slug: 'dl-ellanse-s',
    active: true,
  },
  {
    id: '16',
    name: 'DL HIALUROX BIO 1ML',
    price_pix: 350,
    price_prazo: 399,
    price_card: 399,
    category: 'Bioestimuladores',
    slug: 'dl-hialurox-bio-1ml',
    active: true,
  },
  {
    id: '17',
    name: 'DL NUTRIEX CIENTIFIC',
    price_pix: 310,
    price_prazo: 335,
    price_card: 335,
    category: 'Bioestimuladores',
    slug: 'dl-nutriex-cientific',
    active: true,
  },
  {
    id: '18',
    name: 'DL RADIESSE DUO 1.5CC',
    price_pix: 770,
    price_prazo: 799,
    price_card: 799,
    category: 'Bioestimuladores',
    slug: 'dl-radiesse-duo-1-5cc',
    active: true,
  },
  {
    id: '19',
    name: 'DL RADIESSE DUO 3.0 CC',
    price_pix: 1320,
    price_prazo: 1362,
    price_card: 1362,
    category: 'Bioestimuladores',
    slug: 'dl-radiesse-duo-3-0cc',
    active: true,
  },
  {
    id: '20',
    name: 'DL RADIESSE PLUS LIDO',
    price_pix: 770,
    price_prazo: 779,
    price_card: 779,
    category: 'Bioestimuladores',
    slug: 'dl-radiesse-plus-lido',
    active: true,
  },
  {
    id: '21',
    name: 'DL RENNOVA DIAMOND INTENSE',
    price_pix: 499,
    price_prazo: 519,
    price_card: 519,
    category: 'Bioestimuladores',
    slug: 'dl-rennova-diamond-intense',
    active: true,
  },
  {
    id: '22',
    name: 'DL RENNOVA ELLEVA 150MG',
    price_pix: 569,
    price_prazo: 599,
    price_card: 599,
    category: 'Bioestimuladores',
    slug: 'dl-rennova-elleva-150mg',
    active: true,
  },
  {
    id: '23',
    name: 'DL RENNOVA ELLEVA 210MG',
    price_pix: 799,
    price_prazo: 835,
    price_card: 835,
    category: 'Bioestimuladores',
    slug: 'dl-rennova-elleva-210mg',
    active: true,
  },
  {
    id: '24',
    name: 'DL RENNOVA ELLEVA X 630MG',
    price_pix: 2270,
    price_prazo: 2349,
    price_card: 2349,
    category: 'Bioestimuladores',
    slug: 'dl-rennova-elleva-x-630mg',
    active: true,
  },
  {
    id: '25',
    name: 'DL SCULPTRA 2 FRASCOS',
    price_pix: 2149,
    price_prazo: 2289,
    price_card: 2289,
    category: 'Bioestimuladores',
    slug: 'dl-sculptra-2-frascos',
    active: true,
  },
  {
    id: '26',
    name: 'DL BIO EXO PLUS (EXOSSOMOS PDRN HIALURONICO) 7ML',
    price_pix: 330,
    price_prazo: 359,
    price_card: 359,
    category: 'Bioremodeladores',
    slug: 'dl-bio-exo-plus-7ml',
    active: true,
  },
  {
    id: '27',
    name: 'DL EVO PDRN TRIPLE 1 VIAL 3ML',
    price_pix: 229,
    price_prazo: 245,
    price_card: 245,
    category: 'Bioremodeladores',
    slug: 'dl-evo-pdrn-triple-3ml',
    active: true,
  },
  {
    id: '28',
    name: 'DL PROPHILO 2ML',
    price_pix: 889,
    price_prazo: 916,
    price_card: 916,
    category: 'Bioremodeladores',
    slug: 'dl-prophilo-2ml',
    active: true,
  },
  {
    id: '29',
    name: 'DL REJUVITAL PDRN 5 VIALS 3ML',
    price_pix: 749,
    price_prazo: 799,
    price_card: 799,
    category: 'Bioremodeladores',
    slug: 'dl-rejuvital-pdrn-5-vials',
    active: true,
  },
  {
    id: '30',
    name: 'DL HIALUROX SKIN PLUS 3 VIALS 4ML',
    price_pix: 299,
    price_prazo: 339,
    price_card: 339,
    category: 'Skinboosters',
    slug: 'dl-hialurox-skin-plus-3-vials',
    active: true,
  },
  {
    id: '31',
    name: 'DL SAYPHA RICH',
    price_pix: 199,
    price_prazo: 210,
    price_card: 210,
    category: 'Skinboosters',
    slug: 'dl-saypha-rich',
    active: true,
  },
  {
    id: '32',
    name: 'DL BELOTERO BALANCE LIDO',
    price_pix: 255,
    price_prazo: 265,
    price_card: 265,
    category: 'Preenchedores',
    slug: 'dl-belotero-balance-lido',
    active: true,
  },
  {
    id: '33',
    name: 'DL BELOTERO INTENSE LIDO',
    price_pix: 265,
    price_prazo: 275,
    price_card: 275,
    category: 'Preenchedores',
    slug: 'dl-belotero-intense-lido',
    active: true,
  },
  {
    id: '34',
    name: 'DL BELOTERO VOLUME LIDO',
    price_pix: 525,
    price_prazo: 535,
    price_card: 535,
    category: 'Preenchedores',
    slug: 'dl-belotero-volume-lido',
    active: true,
  },
  {
    id: '35',
    name: 'DL BIO LIFT 24MG',
    price_pix: 159,
    price_prazo: 179,
    price_card: 179,
    category: 'Preenchedores',
    slug: 'dl-bio-lift-24mg',
    active: true,
  },
  {
    id: '36',
    name: 'DL BIOGELIS FINE LINES 2ML',
    price_pix: 460,
    price_prazo: 490,
    price_card: 490,
    category: 'Preenchedores',
    slug: 'dl-biogelis-fine-lines-2ml',
    active: true,
  },
  {
    id: '37',
    name: 'DL BIOGELIS GLOBAL 2ML',
    price_pix: 499,
    price_prazo: 530,
    price_card: 530,
    category: 'Preenchedores',
    slug: 'dl-biogelis-global-2ml',
    active: true,
  },
  {
    id: '38',
    name: 'DL BIOGELIS VOLUME 2ML',
    price_pix: 499,
    price_prazo: 530,
    price_card: 530,
    category: 'Preenchedores',
    slug: 'dl-biogelis-volume-2ml',
    active: true,
  },
  {
    id: '39',
    name: 'DL BIOGELIS VOLUMAX 2ML',
    price_pix: 699,
    price_prazo: 729,
    price_card: 729,
    category: 'Preenchedores',
    slug: 'dl-biogelis-volumax-2ml',
    active: true,
  },
  {
    id: '40',
    name: 'DL BIOGELIS GLOBAL 2X 1,25ML',
    price_pix: 550,
    price_prazo: 569,
    price_card: 569,
    category: 'Preenchedores',
    slug: 'dl-biogelis-global-2x-1-25ml',
    active: true,
  },
  {
    id: '41',
    name: 'DL BIOGELIS VOLUME 2X 1,25ML',
    price_pix: 550,
    price_prazo: 569,
    price_card: 569,
    category: 'Preenchedores',
    slug: 'dl-biogelis-volume-2x-1-25ml',
    active: true,
  },
  {
    id: '42',
    name: 'EPTQ S300',
    price_pix: 285,
    price_prazo: 299,
    price_card: 299,
    category: 'Preenchedores',
    slug: 'eptq-s300',
    active: true,
  },
  {
    id: '43',
    name: 'EPTQ S500',
    price_pix: 285,
    price_prazo: 299,
    price_card: 299,
    category: 'Preenchedores',
    slug: 'eptq-s500',
    active: true,
  },
  {
    id: '44',
    name: 'DL EVO DERM 1ML',
    price_pix: 227,
    price_prazo: 238,
    price_card: 238,
    category: 'Preenchedores',
    slug: 'dl-evo-derm-1ml',
    active: true,
  },
  {
    id: '45',
    name: 'DL EVO ULTRA DEEP 1ML',
    price_pix: 227,
    price_prazo: 238,
    price_card: 238,
    category: 'Preenchedores',
    slug: 'dl-evo-ultra-deep-1ml',
    active: true,
  },
  {
    id: '46',
    name: 'DL NEURAMIS DEEP',
    price_pix: 199,
    price_prazo: 219,
    price_card: 219,
    category: 'Preenchedores',
    slug: 'dl-neuramis-deep',
    active: true,
  },
  {
    id: '47',
    name: 'DL NEURAMIS LIDOCAINE VOLUME',
    price_pix: 199,
    price_prazo: 219,
    price_card: 219,
    category: 'Preenchedores',
    slug: 'dl-neuramis-lidocaine-volume',
    active: true,
  },
  {
    id: '48',
    name: 'DL NEURAMIS LIDOCAINE',
    price_pix: 199,
    price_prazo: 219,
    price_card: 219,
    category: 'Preenchedores',
    slug: 'dl-neuramis-lidocaine',
    active: true,
  },
  {
    id: '49',
    name: 'DL PERFECTHA SUBSKIN',
    price_pix: 730,
    price_prazo: 749,
    price_card: 749,
    category: 'Preenchedores',
    slug: 'dl-perfectha-subskin',
    active: true,
  },
  {
    id: '50',
    name: 'DL RENNOVA HYALURONIC 30 3ML (RBS)',
    price_pix: 345,
    price_prazo: 369,
    price_card: 369,
    category: 'Preenchedores',
    slug: 'dl-rennova-hyaluronic-30-3ml',
    active: true,
  },
  {
    id: '51',
    name: 'DL RENNOVA DEEP LINE LIDO',
    price_pix: 275,
    price_prazo: 295,
    price_card: 295,
    category: 'Preenchedores',
    slug: 'dl-rennova-deep-line-lido',
    active: true,
  },
  {
    id: '52',
    name: 'DL RENNOVA FILL',
    price_pix: 199,
    price_prazo: 215,
    price_card: 215,
    category: 'Preenchedores',
    slug: 'dl-rennova-fill',
    active: true,
  },
  {
    id: '53',
    name: 'DL RENNOVA FILL LIDO',
    price_pix: 217,
    price_prazo: 227,
    price_card: 227,
    category: 'Preenchedores',
    slug: 'dl-rennova-fill-lido',
    active: true,
  },
  {
    id: '54',
    name: 'DL RENNOVA LIFT',
    price_pix: 225,
    price_prazo: 237,
    price_card: 237,
    category: 'Preenchedores',
    slug: 'dl-rennova-lift',
    active: true,
  },
  {
    id: '55',
    name: 'DL RENNOVA LIFT LIDO',
    price_pix: 247,
    price_prazo: 257,
    price_card: 257,
    category: 'Preenchedores',
    slug: 'dl-rennova-lift-lido',
    active: true,
  },
  {
    id: '56',
    name: 'DL RENNOVA LIFT PLUS LIDO',
    price_pix: 285,
    price_prazo: 299,
    price_card: 299,
    category: 'Preenchedores',
    slug: 'dl-rennova-lift-plus-lido',
    active: true,
  },
  {
    id: '57',
    name: 'DL RENNOVA LIFT SHAPE 2ML',
    price_pix: 349,
    price_prazo: 375,
    price_card: 375,
    category: 'Preenchedores',
    slug: 'dl-rennova-lift-shape-2ml',
    active: true,
  },
  {
    id: '58',
    name: 'DL RENNOVA ULTRA VOLUME LIDO 1ML',
    price_pix: 285,
    price_prazo: 299,
    price_card: 299,
    category: 'Preenchedores',
    slug: 'dl-rennova-ultra-volume-lido-1ml',
    active: true,
  },
  {
    id: '59',
    name: 'DL RENNOVA ULTRA VOLUME LIDO 2ML',
    price_pix: 460,
    price_prazo: 488,
    price_card: 488,
    category: 'Preenchedores',
    slug: 'dl-rennova-ultra-volume-lido-2ml',
    active: true,
  },
  {
    id: '60',
    name: 'DL RESTYLANE DEFYNE 1ML',
    price_pix: 420,
    price_prazo: 449,
    price_card: 449,
    category: 'Preenchedores',
    slug: 'dl-restylane-defyne-1ml',
    active: true,
  },
  {
    id: '61',
    name: 'DL RESTYLANE GEL',
    price_pix: 285,
    price_prazo: 308,
    price_card: 308,
    category: 'Preenchedores',
    slug: 'dl-restylane-gel',
    active: true,
  },
  {
    id: '62',
    name: 'DL RESTYLANE LYFT LIDO',
    price_pix: 399,
    price_prazo: 419,
    price_card: 419,
    category: 'Preenchedores',
    slug: 'dl-restylane-lyft-lido',
    active: true,
  },
  {
    id: '63',
    name: 'DL RESTYLANE LYFT SEM LIDO',
    price_pix: 389,
    price_prazo: 409,
    price_card: 409,
    category: 'Preenchedores',
    slug: 'dl-restylane-lyft-sem-lido',
    active: true,
  },
  {
    id: '64',
    name: 'DL RESTYLANE REFYNE 1ML',
    price_pix: 299,
    price_prazo: 320,
    price_card: 320,
    category: 'Preenchedores',
    slug: 'dl-restylane-refyne-1ml',
    active: true,
  },
  {
    id: '65',
    name: 'DL RESTYLANE VOLYME 1ML',
    price_pix: 400,
    price_prazo: 439,
    price_card: 439,
    category: 'Preenchedores',
    slug: 'dl-restylane-volyme-1ml',
    active: true,
  },
  {
    id: '66',
    name: 'DL SAYPHA FILLER LIDO',
    price_pix: 220,
    price_prazo: 231,
    price_card: 231,
    category: 'Preenchedores',
    slug: 'dl-saypha-filler-lido',
    active: true,
  },
  {
    id: '67',
    name: 'DL SAYPHA FILLER SEM LIDO',
    price_pix: 225,
    price_prazo: 235,
    price_card: 235,
    category: 'Preenchedores',
    slug: 'dl-saypha-filler-sem-lido',
    active: true,
  },
  {
    id: '68',
    name: 'DL SAYPHA VOLUME PLUS LIDO',
    price_pix: 264,
    price_prazo: 274,
    price_card: 274,
    category: 'Preenchedores',
    slug: 'dl-saypha-volume-plus-lido',
    active: true,
  },
  {
    id: '69',
    name: 'DL SINGDERM 10ML',
    price_pix: 1100,
    price_prazo: 1190,
    price_card: 1190,
    category: 'Preenchedores',
    slug: 'dl-singderm-10ml',
    active: true,
  },
  {
    id: '70',
    name: 'DL SINGDERM 2ML',
    price_pix: 350,
    price_prazo: 369,
    price_card: 369,
    category: 'Preenchedores',
    slug: 'dl-singderm-2ml',
    active: true,
  },
  {
    id: '71',
    name: 'DL SOFIDERM SUB SKIN 10ML',
    price_pix: 1790,
    price_prazo: 1880,
    price_card: 1880,
    category: 'Preenchedores',
    slug: 'dl-sofiderm-sub-skin-10ml',
    active: true,
  },
  {
    id: '72',
    name: 'DL YVOIRE CLASSIC PLUS',
    price_pix: 299,
    price_prazo: 309,
    price_card: 309,
    category: 'Preenchedores',
    slug: 'dl-yvoire-classic-plus',
    active: true,
  },
  {
    id: '73',
    name: 'DL YVOIRE CONTOUR',
    price_pix: 325,
    price_prazo: 335,
    price_card: 335,
    category: 'Preenchedores',
    slug: 'dl-yvoire-contour',
    active: true,
  },
  {
    id: '74',
    name: 'DL YVOIRE VOLUME PLUS',
    price_pix: 309,
    price_prazo: 329,
    price_card: 329,
    category: 'Preenchedores',
    slug: 'dl-yvoire-volume-plus',
    active: true,
  },
  {
    id: '75',
    name: 'DL APRIL BRIDE 18GX100MMX160MM ESPICULADO PACK 4 FIOS',
    price_pix: 396,
    price_prazo: 380,
    price_card: 380,
    category: 'Fios Bioestimulação',
    slug: 'dl-april-bride-18g-espiculado-pack-4',
    active: true,
  },
  {
    id: '76',
    name: 'DL APRIL BRIDE 19GX100MMX160MM ESPICULADO PACK 4 FIOS',
    price_pix: 396,
    price_prazo: 380,
    price_card: 380,
    category: 'Fios Bioestimulação',
    slug: 'dl-april-bride-19g-espiculado-pack-4',
    active: true,
  },
  {
    id: '77',
    name: 'DL APRIL BRIDE 29GX40MMX50MM PACK 10 UN',
    price_pix: 180,
    price_prazo: 165,
    price_card: 165,
    category: 'Fios Bioestimulação',
    slug: 'dl-april-bride-29g-pack-10',
    active: true,
  },
  {
    id: '78',
    name: 'DL APRIL BRIDE FILLER 21GX38MMX50MM PACK 4 FIOS',
    price_pix: 375,
    price_prazo: 360,
    price_card: 360,
    category: 'Fios Bioestimulação',
    slug: 'dl-april-bride-filler-21g-38mm-pack-4',
    active: true,
  },
  {
    id: '79',
    name: 'DL APRIL BRIDE FILLER 21GX60MMX80MM PACK 4 FIOS',
    price_pix: 375,
    price_prazo: 360,
    price_card: 360,
    category: 'Fios Bioestimulação',
    slug: 'dl-april-bride-filler-21g-60mm-pack-4',
    active: true,
  },
  {
    id: '80',
    name: 'DL BIOFILS LISO AGULHADO 30GX25MMX30MM PACK 10 UN',
    price_pix: 260,
    price_prazo: 240,
    price_card: 240,
    category: 'Fios Bioestimulação',
    slug: 'dl-biofils-liso-30g-pack-10',
    active: true,
  },
  {
    id: '81',
    name: 'DL BIOFILS 19GX100MMX170MM ESPICULADO PACK 4UN',
    price_pix: 375,
    price_prazo: 349,
    price_card: 349,
    category: 'Fios Bioestimulação',
    slug: 'dl-biofils-19g-espiculado-pack-4',
    active: true,
  },
  {
    id: '82',
    name: 'DL BIOFILS 23GX38MMX50MM FILLER PACK 4UN',
    price_pix: 375,
    price_prazo: 349,
    price_card: 349,
    category: 'Fios Bioestimulação',
    slug: 'dl-biofils-23g-filler-pack-4',
    active: true,
  },
  {
    id: '83',
    name: 'DL ITHREAD 21GX38MMX50MM FILLER PACK 20UN',
    price_pix: 1969,
    price_prazo: 1838,
    price_card: 1838,
    category: 'Fios Bioestimulação',
    slug: 'dl-ithread-21g-38mm-pack-20',
    active: true,
  },
  {
    id: '84',
    name: 'DL ITHREAD 21GX60MMX90MM FILLER PACK 20UN',
    price_pix: 1969,
    price_prazo: 1838,
    price_card: 1838,
    category: 'Fios Bioestimulação',
    slug: 'dl-ithread-21g-60mm-pack-20',
    active: true,
  },
  {
    id: '85',
    name: 'DL ITHREAD 29GX38MM AGULHADO PACK 20UN',
    price_pix: 499,
    price_prazo: 460,
    price_card: 460,
    category: 'Fios Bioestimulação',
    slug: 'dl-ithread-29g-38mm-pack-20',
    active: true,
  },
  {
    id: '86',
    name: 'DL ITHREAD 30GX25MM AGULHADO PACK 20UN',
    price_pix: 499,
    price_prazo: 460,
    price_card: 460,
    category: 'Fios Bioestimulação',
    slug: 'dl-ithread-30g-25mm-pack-20',
    active: true,
  },
  {
    id: '87',
    name: 'DL ITHREAD ESPICULADO 19GX100X160MM PACK 20UN',
    price_pix: 1899,
    price_prazo: 1820,
    price_card: 1820,
    category: 'Fios Bioestimulação',
    slug: 'dl-ithread-espiculado-19g-pack-20',
    active: true,
  },
  {
    id: '88',
    name: 'DL MICROCÂNULA PRO DEEP (22GX50MM)',
    price_pix: 15,
    price_prazo: 17,
    price_card: 17,
    category: 'Microcânulas',
    slug: 'dl-microcanula-22g-50mm',
    active: true,
  },
  {
    id: '89',
    name: 'DL MICROCÂNULA PRO DEEP (25GX50MM)',
    price_pix: 15,
    price_prazo: 17,
    price_card: 17,
    category: 'Microcânulas',
    slug: 'dl-microcanula-25g-50mm',
    active: true,
  },
  {
    id: '90',
    name: 'DL MICROCÂNULA PRO DEEP (22GX70MM)',
    price_pix: 15,
    price_prazo: 17,
    price_card: 17,
    category: 'Microcânulas',
    slug: 'dl-microcanula-22g-70mm',
    active: true,
  },
  {
    id: '91',
    name: 'DL MICROCÂNULA PRO DEEP (18GX100MM)',
    price_pix: 18,
    price_prazo: 20,
    price_card: 20,
    category: 'Microcânulas',
    slug: 'dl-microcanula-18g-100mm',
    active: true,
  },
  {
    id: '92',
    name: 'DL MICROCÂNULA PRO DEEP (18GX70MM)',
    price_pix: 18,
    price_prazo: 20,
    price_card: 20,
    category: 'Microcânulas',
    slug: 'dl-microcanula-18g-70mm',
    active: true,
  },
  {
    id: '93',
    name: 'DL HIALURONIDASE 3 VIALS 2.000 UTR',
    price_pix: 170,
    price_prazo: 180,
    price_card: 180,
    category: 'Enzimas',
    slug: 'dl-hialuronidase-3-vials',
    active: true,
  },
];
