CREATE TABLE PRODUCTS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    NAME TEXT NOT NULL,
    SLUG TEXT UNIQUE NOT NULL,
    PRICE_PIX DECIMAL(10, 2) NOT NULL,
    PRICE_PRAZO DECIMAL(10, 2) NOT NULL,
    DESCRIPTION TEXT,
    IMAGES TEXT[] DEFAULT '{}',
    CATEGORY TEXT NOT NULL CHECK (CATEGORY IN ( 'Toxina Botulínica', 'Bioestimulador', 'Bioremodelador', 'Skinbooster', 'Preenchedor', 'Fio Bioestimulador', 'Fio Bioestimulação', 'Microcânula', 'Enzima' )),
    ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE PRODUCTS ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read products" ON PRODUCTS FOR SELECT USING (TRUE);

CREATE POLICY "Auth insert products" ON PRODUCTS FOR INSERT WITH CHECK (AUTH.ROLE() = 'authenticated');

CREATE POLICY "Auth update products" ON PRODUCTS FOR UPDATE USING (AUTH.ROLE() = 'authenticated');

CREATE POLICY "Auth delete products" ON PRODUCTS FOR DELETE USING (AUTH.ROLE() = 'authenticated');