CREATE TABLE ORDERS (
    ID UUID PRIMARY KEY DEFAULT UUID_GENERATE_V4(),
    CUSTOMER_NAME TEXT,
    CUSTOMER_PHONE TEXT,
    ITEMS JSONB NOT NULL,
    TOTAL DECIMAL(10, 2) NOT NULL,
    PDF_URL TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE ORDERS ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Auth insert orders" ON ORDERS FOR INSERT WITH CHECK (AUTH.ROLE() = 'authenticated');

CREATE POLICY "Public read orders" ON ORDERS FOR SELECT USING (TRUE);

-- Pra admin ver