CREATE VIEW POPULAR_PRODUCTS AS
    SELECT
        NAME,
        CATEGORY,
        VIEWS_COUNT,
        STOCK
    FROM
        PRODUCTS
    ORDER BY
        VIEWS_COUNT DESC LIMIT 10;

CREATE VIEW ORDER_SUMMARY AS
    SELECT
        STATUS,
        COUNT(*)   AS COUNT,
        SUM(TOTAL) AS REVENUE
    FROM
        ORDERS
    GROUP BY
        STATUS;

CREATE OR REPLACE FUNCTION INCREMENT_VIEWS(
    PROD_ID UUID
) RETURNS VOID AS
    $$  BEGIN UPDATE PRODUCTS SET VIEWS_COUNT = VIEWS_COUNT + 1 WHERE ID = PROD_ID;
END;
$$  LANGUAGE PLPGSQL SECURITY DEFINER;