CREATE TABLE IF NOT EXISTS ADMIN_CONFIG (
    ID SERIAL PRIMARY KEY,
    PASSWORD_HASH TEXT NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Permitir apenas 1 registro (senha única global)
CREATE UNIQUE INDEX IF NOT EXISTS IDX_ADMIN_CONFIG_SINGLETON ON ADMIN_CONFIG((1));